In [67]:
import pandas as pd

df = pd.read_csv("data/title_fights.csv")

df

          winner       loser  year weight
0       aspinall     blaydes  2024     hw
1       aspinall   pavlovich  2023     hw
2          jones        gane  2023     hw
3        ngannou        gane  2021     hw
4        ngannou      miocic  2021     hw
..           ...         ...   ...    ...
337  jedrzejczyk     gadelha  2016    wsw
338  jedrzejczyk  letourneau  2015    wsw
339  jedrzejczyk       penne  2015    wsw
340  jedrzejczyk     esparza  2015    wsw
341      esparza   namajunas  2014    wsw

[342 rows x 4 columns]

In [68]:
pivot = df.pivot_table(index='year', columns='weight', values='winner', aggfunc='count')
pivot.index.name = 'year'

for weight in pivot.columns:
    first_year = min(year for year in pivot.index if not pd.isna(pivot.loc[year, weight]))
    pivot.loc[pivot.index > first_year, weight] = pivot.loc[pivot.index > first_year, weight].fillna(0)
    
pivot["sum"] = pivot.sum(axis=1)
pivot["avg"] = round(pivot.drop("sum", axis=1).mean(axis=1),1)
pivot.to_csv('data/title_fights_per_year.csv')
pivot

weight   bw  flw   fw   hw  lhw   lw   mw  wbw  wflw  wsw   ww   sum  avg
year
1997    NaN  NaN  NaN  4.0  1.0  NaN  NaN  NaN   NaN  NaN  NaN   5.0  2.5
1998    NaN  NaN  NaN  0.0  3.0  NaN  NaN  NaN   NaN  NaN  1.0   4.0  1.3
1999    NaN  NaN  NaN  2.0  1.0  NaN  NaN  NaN   NaN  NaN  2.0   5.0  1.7
2000    NaN  NaN  NaN  2.0  2.0  NaN  NaN  NaN   NaN  NaN  2.0   6.0  2.0
2001    NaN  NaN  NaN  2.0  3.0  2.0  1.0  NaN   NaN  NaN  2.0  10.0  2.0
2002    NaN  NaN  NaN  2.0  1.0  1.0  1.0  NaN   NaN  NaN  3.0   8.0  1.6
2003    NaN  NaN  NaN  2.0  2.0  0.0  0.0  NaN   NaN  NaN  2.0   6.0  1.2
2004    NaN  NaN  NaN  1.0  2.0  0.0  0.0  NaN   NaN  NaN  2.0   5.0  1.0
2005    NaN  NaN  NaN  3.0  2.0  0.0  3.0  NaN   NaN  NaN  1.0   9.0  1.8
2006    NaN  NaN  NaN  3.0  3.0  1.0  2.0  NaN   NaN  NaN  2.0  11.0  2.2
2007    NaN  NaN  NaN  2.0  2.0  1.0  2.0  NaN   NaN  NaN  1.0   8.0  1.6
2008    NaN  NaN  NaN  0.0  2.0  2.0  2.0  NaN   NaN  NaN  2.0   8.0  1.6
2009    NaN  NaN  NaN  1.0  2.0  2.0  1.0  NaN   NaN  NaN  2.0   8.0  1.6
2010    1.0  NaN  2.0  2.0  1.0  2.0  2.0  NaN   NaN  NaN  2.0  12.0  1.7
2011    2.0  NaN  2.0  1.0  3.0  2.0  2.0  NaN   NaN  NaN  1.0  13.0  1.9
2012    0.0  1.0  1.0  2.0  2.0  3.0  1.0  NaN   NaN  NaN  1.0  11.0  1.4
2013    0.0  3.0  2.0  1.0  2.0  2.0  2.0  2.0   NaN  NaN  2.0  16.0  1.8
2014    3.0  2.0  2.0  1.0  1.0  1.0  1.0  2.0   NaN  1.0  2.0  16.0  1.6
2015    1.0  2.0  1.0  1.0  3.0  2.0  2.0  3.0   NaN  3.0  1.0  19.0  1.9
2016    3.0  2.0  0.0  2.0  1.0  2.0  1.0  3.0   NaN  2.0  3.0  19.0  1.9
2017    1.0  2.0  1.0  1.0  2.0  0.0  1.0  1.0   1.0  2.0  2.0  14.0  1.3
2018    1.0  1.0  1.0  3.0  2.0  2.0  0.0  1.0   1.0  1.0  1.0  14.0  1.3
2019    1.0  1.0  2.0  1.0  2.0  1.0  2.0  2.0   2.0  1.0  2.0  17.0  1.5
2020    2.0  3.0  1.0  1.0  2.0  1.0  2.0  0.0   2.0  2.0  1.0  17.0  1.5
2021    1.0  1.0  1.0  2.0  2.0  2.0  1.0  1.0   2.0  2.0  3.0  18.0  1.6
2022    2.0  1.0  2.0  0.0  1.0  1.0  3.0  1.0   1.0  2.0  1.0  15.0  1.4
2023    2.0  3.0  1.0  2.0  2.0  2.0  2.0  1.0   2.0  1.0  2.0  20.0  1.8
2024    2.0  2.0  2.0  1.0  3.0  1.0  2.0  2.0   1.0  1.0  1.0  18.0  1.6
2025    2.0  0.0  1.0  0.0  1.0  1.0  1.0  1.0   1.0  1.0  1.0  10.0  0.9